from backend.agents.state import InvestigationState
from backend.agents.llm import model
from pydantic import BaseModel
import json

from backend.tools.metrics import get_service_metrics
from backend.tools.logs import get_recent_logs
from backend.tools.deployments import get_recent_deployments
from backend.tools.database import get_database_health


class Hypothesis(BaseModel):
    cause: str
    confidence: float
    supporting_evidence: list[str]


class HypothesisEvaluation(BaseModel):
    hypothesis: str
    supported: bool
    reason: str


# First node in the investigation workflow.
# Its job is to move an OPEN incident into the
# INVESTIGATING state.
def start_investigation(state: InvestigationState):

    # Update the incident status to indicate that
    # Veytra has started investigating the incident.
    state["status"] = "INVESTIGATING"

    # Return the updated state so LangGraph can pass
    # it to the next node.
    return state


# Collect service metrics as the first piece of
# operational evidence for the investigation.
def collect_metrics(state: InvestigationState):

    # Fetch metrics for the service involved in the incident.
    metrics = get_service_metrics(state["service"])

    # Store the metrics in the shared evidence list.
    state["evidence"].append({
        "type": "metrics",
        "data": metrics,
    })

    # Return the updated state to the next LangGraph node.
    return state


# Collect recent application logs as another piece of
# operational evidence for the investigation.
def collect_logs(state: InvestigationState):

    # Fetch recent logs for the affected service.
    logs = get_recent_logs(state["service"])

    # Append the logs to the existing evidence.
    state["evidence"].append({
        "type": "logs",
        "data": logs,
    })

    # Return the updated state to the next node.
    return state


# Collect recent deployments as another piece of
# operational evidence for the investigation.
def collect_deployments(state: InvestigationState):

    # Fetch recent deployments for the affected service.
    deployments = get_recent_deployments(state["service"])

    # Append deployment information to the existing evidence.
    state["evidence"].append({
        "type": "deployments",
        "data": deployments,
    })

    # Return the updated state to the next node.
    return state


# Collect database health as another piece of
# operational evidence for the investigation.
def collect_database_health(state: InvestigationState):

    # Fetch database health for the affected service.
    database_health = get_database_health(state["service"])

    # Append database health to the existing evidence.
    state["evidence"].append({
        "type": "database_health",
        "data": database_health,
    })

    # Return the updated state to the next node.
    return state


# Generate possible causes for the incident using
# the evidence collected by the investigation.
def generate_hypotheses(state: InvestigationState):

    # Get all evidence collected during the investigation.
    evidence = state["evidence"]

    # Convert the evidence into text that we can provide
    # to the language model.
    evidence_text = str(evidence)

    # Create instructions for the LLM to analyze the evidence
    # and propose possible causes of the incident.
    prompt = f"""
    You are an incident investigation assistant.

    Analyze the following evidence and generate possible
    root-cause hypotheses for the incident.

    Evidence:
    {evidence_text}

    For each hypothesis, return a JSON object with exactly these fields:
    - cause
    - confidence: a number between 0 and 1
    - supporting_evidence: a list of at most 2 short evidence statements

    Keep each evidence statement under 15 words.
    Do not include raw Python dictionaries or JSON inside supporting_evidence.
    Generate at most 3 hypotheses.
    Keep the entire response concise.

    Return the hypotheses as a JSON array.
    Do not include any other text.

    Do not recommend or execute any remediation action.
    """

    # Send the evidence and instructions to the LLM.
    response = model.invoke(prompt)

    # Get the text generated by the LLM.
    hypothesis_text = response.content.strip()

    # DEBUG: Inspect the raw hypothesis response from the LLM.
    print("RAW HYPOTHESES:", hypothesis_text)

    # Find the beginning of the JSON array.
    #
    # This handles responses such as:
    #
    # ```
    # [
    #     {...}
    # ]
    # ```
    #
    # and:
    #
    # ```json
    # [
    #     {...}
    # ]
    # ```
    #
    # It also handles cases where the LLM adds
    # explanatory text before or after the JSON.
    json_start = hypothesis_text.find("[")

    # Find the end of the JSON array.
    json_end = hypothesis_text.rfind("]")

    # Keep only the JSON array.
    if json_start != -1 and json_end != -1:
        hypothesis_text = hypothesis_text[json_start:json_end + 1]

    # Remove any extra whitespace after cleanup.
    hypothesis_text = hypothesis_text.strip()

    # Convert the JSON string returned by the LLM
    # into Python data.
    hypotheses_data = json.loads(hypothesis_text)

    # Validate each hypothesis using our Pydantic schema.
    validated_hypotheses = [
        Hypothesis(**hypothesis)
        for hypothesis in hypotheses_data
    ]

    # DEBUG: Check what Pydantic produced.
    print("VALIDATED HYPOTHESES:", validated_hypotheses)

    # Convert the validated Pydantic objects into dictionaries
    # because our LangGraph state expects list[dict].
    state["hypotheses"] = [
        hypothesis.model_dump()
        for hypothesis in validated_hypotheses
    ]

    # Return the updated state to LangGraph.
    return state


# Evaluate the hypotheses generated by the LLM against
# the evidence collected during the investigation.
def evaluate_hypotheses(state: InvestigationState):

    # Get the hypotheses generated by the previous node.
    # These are the possible explanations we want to evaluate.
    hypotheses = state["hypotheses"]

    # Get all operational evidence collected so far.
    # The LLM will use this evidence to evaluate the hypotheses.
    evidence = state["evidence"]

    # Convert the Python data into text so it can be
    # included in the LLM prompt.
    hypotheses_text = str(hypotheses)
    evidence_text = str(evidence)

    # Create instructions for the LLM.
    # The LLM will determine whether the available evidence
    # supports each hypothesis.
    prompt = f"""
    You are an incident investigation assistant.

    Evaluate the following hypotheses using the available evidence.

    Hypotheses:
    {hypotheses_text}

    Evidence:
    {evidence_text}

    For each hypothesis, return a JSON object with exactly these fields:
    - hypothesis: the hypothesis cause as a short string
    - supported: true or false
    - reason: one short sentence

    Return the evaluations as a JSON array.

    Keep the reason under 20 words.
    Do not repeat the evidence inside the hypothesis field.
    Do not include confidence or supporting_evidence in the evaluation.
    Do not include any other text.

    Do not recommend or execute any remediation action.
    """

    # Send the hypotheses and evidence to the LLM
    # and receive its evaluation.
    response = model.invoke(prompt)

    # Get the text generated by the LLM.
    evaluation_text = response.content.strip()

    # DEBUG: Inspect the raw evaluation returned by the LLM.
    print("RAW EVALUATION:", evaluation_text)

    # Remove Markdown JSON code fences if the LLM
    # wraps the JSON response inside ```json ... ```.
    if evaluation_text.startswith("```json"):
        evaluation_text = evaluation_text[7:]

    if evaluation_text.endswith("```"):
        evaluation_text = evaluation_text[:-3]

    # Remove any extra whitespace after cleanup.
    evaluation_text = evaluation_text.strip()

    # Find the beginning of the JSON array.
    json_start = evaluation_text.find("[")

    # Find the end of the JSON array.
    json_end = evaluation_text.rfind("]")

    # Keep only the JSON array.
    #
    # This prevents errors when the LLM returns something like:
    #
    # Here is the evaluation:
    #
    # [
    #     {...}
    # ]
    #
    # We extract only the [...] portion because our
    # Pydantic validation expects a list of evaluations.
    if json_start != -1 and json_end != -1:
        evaluation_text = evaluation_text[json_start:json_end + 1]

    # Convert the JSON string returned by the LLM
    # into normal Python data.
    evaluation_data = json.loads(evaluation_text)

    # Validate each evaluation using our Pydantic schema.
    validated_evaluations = [
        HypothesisEvaluation(**evaluation)
        for evaluation in evaluation_data
    ]

    # Convert the validated Pydantic objects into dictionaries
    # because our LangGraph state expects list[dict].
    state["evaluation"] = [
        evaluation.model_dump()
        for evaluation in validated_evaluations
    ]

    # Return the updated state to LangGraph.
    return state


# Decide what should happen next based on the hypothesis evaluation.
def make_decision(state: InvestigationState):
    evaluations = state["evaluation"]

    supported_hypotheses = [
        evaluation
        for evaluation in evaluations
        if evaluation["supported"]
    ]

    if supported_hypotheses:
        state["root_cause"] = supported_hypotheses[0]["hypothesis"]
        state["decision"] = "REMEDIATION_REQUIRED"
    else:
        state["decision"] = "CONTINUE_INVESTIGATION"

    return state