from typing import TypedDict


# Shared state carried between LangGraph nodes
# during an incident investigation.
class InvestigationState(TypedDict):

    # Unique identifier of the incident being investigated.
    incident_id: str

    # Service affected by the incident.
    service: str

    # Severity level of the incident.
    severity: str

    # Current stage/status of the incident investigation.
    status: str

    # Evidence collected from tools during the investigation.
    evidence: list[dict]

    # Possible root-cause explanations generated by the LLM.
    hypotheses: list[dict]

    # Evaluation of how strongly the evidence supports each hypothesis.
    evaluation: list[dict]

    #decision with the investigation result
    decision: str

    #we will add the remediation method
    remediation: dict

    # Stores the human approval decision.
    # Expected values:
    # PENDING, APPROVED, or REJECTED.
    approval: str